name: Azure Static Web Apps CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_publish_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci

      - name: Sets cypress env vars for PR
        run: |
          echo "COMMIT_INFO_MESSAGE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "COMMIT_INFO_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "COMMIT_INFO_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/master'

      # Build demo apps, libs, storybook and docs...
      - name: "Run linting and builds"
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,build,build-storybook,compodoc
          parallel: true
          nxCloud: true

      - name: "Run e2e"
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: e2e
          parallel: false
          nxCloud: true
          args: '--configuration=ci'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Publish angular-swa-auth library...
      - name: "Check library affected"
        id: check_library_affected
        uses: andstor/file-existence-action@v1
        with:
          files: "./dist/libs/public/angular-swa-auth/package.json"
      - name: publish angular-swa-auth npm package
        if: github.ref == 'refs/heads/master' && steps.check_library_affected.outputs.files_exists == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/libs/public/angular-swa-auth/package.json
          access: public
          check-version: true
      - name: publish angular-swa-auth npm package (dry run)
        if: github.ref != 'refs/heads/master' && steps.check_library_affected.outputs.files_exists == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/libs/public/angular-swa-auth/package.json
          access: public
          check-version: false
          dry-run: true

      # Publish angular-swa-auth-e2e-util library...
      - name: "Check e2e library affected"
        id: check_e2e_library_affected
        uses: andstor/file-existence-action@v1
        with:
          files: "./dist/libs/public/angular-swa-auth-e2e-util/package.json"
      - name: publish angular-swa-auth-e2e-util npm package
        if: github.ref == 'refs/heads/master' && steps.check_e2e_library_affected.outputs.files_exists == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/libs/public/angular-swa-auth-e2e-util/package.json
          access: public
          check-version: true
      - name: publish angular-swa-auth-e2e-util npm package (dry run)
        if: github.ref != 'refs/heads/master' && steps.check_e2e_library_affected.outputs.files_exists == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/libs/public/angular-swa-auth-e2e-util/package.json
          access: public
          check-version: false
          dry-run: true

      # Deploy angular-swa-auth-demo site...
      - name: "Check angular-swa-auth-demo app affected"
        id: check_demo_app_affected
        uses: andstor/file-existence-action@v1
        with:
          files: "./dist/apps/angular-swa-auth-demo/index.html"
      - name: Deploy angular-swa-auth-demo app
        if: steps.check_demo_app_affected.outputs.files_exists == 'true'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MUSHROOM_090FBBE10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist/apps/angular-swa-auth-demo" # App source code path
          config_file_location: "/apps/angular-swa-auth-demo"
          api_location: "api" # Api source code path - optional
          skip_app_build: true
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      # Deploy angular-swa-auth-nolib site...
      - name: "Check angular-swa-auth-nolib app affected"
        id: check_nolib_app_affected
        uses: andstor/file-existence-action@v1
        with:
          files: "./dist/apps/angular-swa-auth-nolib/index.html"
      - name: Deploy angular-swa-auth-nolib app
        if: steps.check_nolib_app_affected.outputs.files_exists == 'true'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_WATER_05AF79A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist/apps/angular-swa-auth-nolib" # App source code path
          config_file_location: "/apps/angular-swa-auth-nolib"
          api_location: "" # There is a problem trying to build the api again (its already been built above; following this issue to resolve: https://github.com/Azure/static-web-apps/issues/343
          skip_app_build: true
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      # Deploy storybook site...
      - name: "Check storybook affected"
        id: check_storybook_affected
        uses: andstor/file-existence-action@v1
        with:
          files: "./dist/storybook/public-angular-swa-auth/index.html"
      - name: Deploy storybook app
        if: steps.check_storybook_affected.outputs.files_exists == 'true'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_DUNE_078458A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist/storybook/public-angular-swa-auth" # App source code path
          api_location: "" # Api source code path - optional
          skip_app_build: true
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      # Deploy docs site...
      - name: "Check docs affected"
        id: check_docs_affected
        uses: andstor/file-existence-action@v1
        with:
          files: "./dist/compodoc/public-angular-swa-auth/index.html"
      - name: Deploy documentation app
        if: steps.check_docs_affected.outputs.files_exists == 'true'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FLOWER_0685E8810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist/compodoc/public-angular-swa-auth" # App source code path
          api_location: "" # Api source code path - optional
          skip_app_build: true
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Delete angular-swa-auth-demo PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MUSHROOM_090FBBE10 }}
          action: "close"
      - name: Delete angular-swa-auth-nolib PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_WATER_05AF79A10 }}
          action: "close"
      - name: Delete storybook PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_DUNE_078458A10 }}
          action: "close"
      - name: Delete docs PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FLOWER_0685E8810 }}
          action: "close"
